
###
GET http://localhost:8000/

###
GET http://localhost:8000/database

// ----------------------------------------------- Fleets -----------------------------
###
GET http://localhost:8000/fleets

###
POST http://localhost:8000/fleets
Content-Type: application/json

{
    "name": "Veículos de Resgate",
    "max_speed": 120
}

// ----------------------------------------------- Alert -----------------------------
###
GET http://localhost:8000/fleets/1/alerts

###
POST http://localhost:8000/fleets/1/alerts
Content-Type: application/json

{ 
    "webhook": "http://localhost:8000/webhook"
}

// ----------------------------------------------- Vehicle -----------------------------
###
GET http://localhost:8000/vehicles

###
POST http://localhost:8000/vehicles
Content-Type: application/json

{
    "fleet_id": 1, "name": "veículo 1", "max_speed": 70.3
}


// -----------------------------------------------Positions -----------------------------
###
GET http://localhost:8000/vehicles/1/positions

###
POST http://localhost:8000/vehicles/1/positions
Content-Type: application/json

{
    "timestamp": "2022-10-05 14:48:00.000", 
    "latitude": 39.10398,
    "longitude": 3.17403,
    "current_speed": 120.5

}